on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled]
  pull_request_review:
    types: [submitted]

name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  ci-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-bun
      - uses: ./.github/actions/build
      - uses: ./.github/actions/prevent-uncommit-changes
      - run: bun test
      - run: bun run lint
