on:
  push:
    branches:
      - main

name: Semantic Release

permissions:
  contents: read # For Checkout

jobs:
  release:
    permissions:
      contents: write # to create release commit (googleapis/release-please-action)
      pull-requests: write # to create release PR (googleapis/release-please-action)
      pages: write # to deploy to GitHub Pages

    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/config/release-please-config.json
          manifest-file: .github/config/.release-please-config.json
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun --bun run build
      - run: bun test

      - name: Build release with versioned base path
        if: ${{ steps.release.outputs.release_created }}
        run: bun --bun run build
        env:
          VITE_BASE_PATH: /warvity/${{ steps.release.outputs.tag_name }}/

      - name: Add .nojekyll
        if: ${{ steps.release.outputs.release_created }}
        run: touch ./dist/.nojekyll

      - name: Deploy release to GitHub Pages (versioned)
        if: ${{ steps.release.outputs.release_created }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ steps.release.outputs.tag_name }}
          keep_files: true
