on:
  push:
    branches:
      - main

name: Semantic Release

permissions:
  contents: read # For Checkout

jobs:
  release:
    permissions:
      contents: write # to create release commit (googleapis/release-please-action)
      pull-requests: write # to create release PR (googleapis/release-please-action)

    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/config/release-please-config.json
          manifest-file: .github/config/.release-please-config.json
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun --bun run build
      - run: bun test
